---
# This is a role for setting up the client.

- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - hydra
     - medusa
    update_cache: yes

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644

- name: Add picture to the home directory
  copy:
    src: gepard.jpg
    dest: /home/user/gepard.jpg
    owner: user
    mode: 0644

...
